// Code generated by protoc-gen-go. DO NOT EDIT.
// source: p2p.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InitialPeer struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Expires              uint64   `protobuf:"varint,2,opt,name=expires,proto3" json:"expires,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitialPeer) Reset()         { *m = InitialPeer{} }
func (m *InitialPeer) String() string { return proto.CompactTextString(m) }
func (*InitialPeer) ProtoMessage()    {}
func (*InitialPeer) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{0}
}

func (m *InitialPeer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitialPeer.Unmarshal(m, b)
}
func (m *InitialPeer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitialPeer.Marshal(b, m, deterministic)
}
func (m *InitialPeer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitialPeer.Merge(m, src)
}
func (m *InitialPeer) XXX_Size() int {
	return xxx_messageInfo_InitialPeer.Size(m)
}
func (m *InitialPeer) XXX_DiscardUnknown() {
	xxx_messageInfo_InitialPeer.DiscardUnknown(m)
}

var xxx_messageInfo_InitialPeer proto.InternalMessageInfo

func (m *InitialPeer) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *InitialPeer) GetExpires() uint64 {
	if m != nil {
		return m.Expires
	}
	return 0
}

type InitialPeerEvents struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitialPeerEvents) Reset()         { *m = InitialPeerEvents{} }
func (m *InitialPeerEvents) String() string { return proto.CompactTextString(m) }
func (*InitialPeerEvents) ProtoMessage()    {}
func (*InitialPeerEvents) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{1}
}

func (m *InitialPeerEvents) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitialPeerEvents.Unmarshal(m, b)
}
func (m *InitialPeerEvents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitialPeerEvents.Marshal(b, m, deterministic)
}
func (m *InitialPeerEvents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitialPeerEvents.Merge(m, src)
}
func (m *InitialPeerEvents) XXX_Size() int {
	return xxx_messageInfo_InitialPeerEvents.Size(m)
}
func (m *InitialPeerEvents) XXX_DiscardUnknown() {
	xxx_messageInfo_InitialPeerEvents.DiscardUnknown(m)
}

var xxx_messageInfo_InitialPeerEvents proto.InternalMessageInfo

type BcBlocks struct {
	Blocks               []*BcBlock `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *BcBlocks) Reset()         { *m = BcBlocks{} }
func (m *BcBlocks) String() string { return proto.CompactTextString(m) }
func (*BcBlocks) ProtoMessage()    {}
func (*BcBlocks) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{2}
}

func (m *BcBlocks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BcBlocks.Unmarshal(m, b)
}
func (m *BcBlocks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BcBlocks.Marshal(b, m, deterministic)
}
func (m *BcBlocks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BcBlocks.Merge(m, src)
}
func (m *BcBlocks) XXX_Size() int {
	return xxx_messageInfo_BcBlocks.Size(m)
}
func (m *BcBlocks) XXX_DiscardUnknown() {
	xxx_messageInfo_BcBlocks.DiscardUnknown(m)
}

var xxx_messageInfo_BcBlocks proto.InternalMessageInfo

func (m *BcBlocks) GetBlocks() []*BcBlock {
	if m != nil {
		return m.Blocks
	}
	return nil
}

// Services: over-the-air OP_X update
// Services: provision authentication module
// Services: enable hardware functionality
// Services: data update
type Service struct {
	Version              uint64   `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Pid                  string   `protobuf:"bytes,3,opt,name=pid,proto3" json:"pid,omitempty"`
	Text                 string   `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Data                 string   `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{3}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Service) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Service) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

func (m *Service) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Service) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

// Update Service: over-the-air OP_X update
// Update Service: provision / authentication module
// Update Service: enable hardware functionality
// Update Service: data update
type PutService struct {
	Version              uint64   `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Pid                  string   `protobuf:"bytes,3,opt,name=pid,proto3" json:"pid,omitempty"`
	Encrypted            bool     `protobuf:"varint,4,opt,name=encrypted,proto3" json:"encrypted,omitempty"`
	Text                 string   `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	Data                 []byte   `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutService) Reset()         { *m = PutService{} }
func (m *PutService) String() string { return proto.CompactTextString(m) }
func (*PutService) ProtoMessage()    {}
func (*PutService) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{4}
}

func (m *PutService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutService.Unmarshal(m, b)
}
func (m *PutService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutService.Marshal(b, m, deterministic)
}
func (m *PutService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutService.Merge(m, src)
}
func (m *PutService) XXX_Size() int {
	return xxx_messageInfo_PutService.Size(m)
}
func (m *PutService) XXX_DiscardUnknown() {
	xxx_messageInfo_PutService.DiscardUnknown(m)
}

var xxx_messageInfo_PutService proto.InternalMessageInfo

func (m *PutService) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *PutService) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *PutService) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

func (m *PutService) GetEncrypted() bool {
	if m != nil {
		return m.Encrypted
	}
	return false
}

func (m *PutService) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *PutService) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Record struct {
	Version              uint64   `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port                 uint64   `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	LastSeen             uint64   `protobuf:"varint,4,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	LastSeenHash         string   `protobuf:"bytes,5,opt,name=last_seen_hash,json=lastSeenHash,proto3" json:"last_seen_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{5}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Record) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Record) GetPort() uint64 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Record) GetLastSeen() uint64 {
	if m != nil {
		return m.LastSeen
	}
	return 0
}

func (m *Record) GetLastSeenHash() string {
	if m != nil {
		return m.LastSeenHash
	}
	return ""
}

type Config struct {
	Version              uint64     `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	SecureAdmin          string     `protobuf:"bytes,2,opt,name=secure_admin,json=secureAdmin,proto3" json:"secure_admin,omitempty"`
	SecureGroup          string     `protobuf:"bytes,3,opt,name=secure_group,json=secureGroup,proto3" json:"secure_group,omitempty"`
	Services             []*Service `protobuf:"bytes,4,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{6}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Config) GetSecureAdmin() string {
	if m != nil {
		return m.SecureAdmin
	}
	return ""
}

func (m *Config) GetSecureGroup() string {
	if m != nil {
		return m.SecureGroup
	}
	return ""
}

func (m *Config) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

type PutConfig struct {
	Version              uint64        `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Admin                bool          `protobuf:"varint,2,opt,name=admin,proto3" json:"admin,omitempty"`
	SecureSignature      string        `protobuf:"bytes,3,opt,name=secure_signature,json=secureSignature,proto3" json:"secure_signature,omitempty"`
	Services             []*PutService `protobuf:"bytes,4,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PutConfig) Reset()         { *m = PutConfig{} }
func (m *PutConfig) String() string { return proto.CompactTextString(m) }
func (*PutConfig) ProtoMessage()    {}
func (*PutConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7fdddb109e6467a, []int{7}
}

func (m *PutConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutConfig.Unmarshal(m, b)
}
func (m *PutConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutConfig.Marshal(b, m, deterministic)
}
func (m *PutConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutConfig.Merge(m, src)
}
func (m *PutConfig) XXX_Size() int {
	return xxx_messageInfo_PutConfig.Size(m)
}
func (m *PutConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_PutConfig.DiscardUnknown(m)
}

var xxx_messageInfo_PutConfig proto.InternalMessageInfo

func (m *PutConfig) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *PutConfig) GetAdmin() bool {
	if m != nil {
		return m.Admin
	}
	return false
}

func (m *PutConfig) GetSecureSignature() string {
	if m != nil {
		return m.SecureSignature
	}
	return ""
}

func (m *PutConfig) GetServices() []*PutService {
	if m != nil {
		return m.Services
	}
	return nil
}

func init() {
	proto.RegisterType((*InitialPeer)(nil), "InitialPeer")
	proto.RegisterType((*InitialPeerEvents)(nil), "InitialPeerEvents")
	proto.RegisterType((*BcBlocks)(nil), "BcBlocks")
	proto.RegisterType((*Service)(nil), "Service")
	proto.RegisterType((*PutService)(nil), "PutService")
	proto.RegisterType((*Record)(nil), "Record")
	proto.RegisterType((*Config)(nil), "Config")
	proto.RegisterType((*PutConfig)(nil), "PutConfig")
}

func init() { proto.RegisterFile("p2p.proto", fileDescriptor_e7fdddb109e6467a) }

var fileDescriptor_e7fdddb109e6467a = []byte{
	// 452 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x86, 0x15, 0x9a, 0x76, 0x93, 0x69, 0x05, 0x8b, 0xe1, 0x10, 0x01, 0x87, 0x10, 0xad, 0x44,
	0x41, 0x4b, 0x2b, 0x2d, 0x4f, 0xb0, 0x45, 0x08, 0xb8, 0x55, 0xee, 0x8d, 0x4b, 0xe5, 0x3a, 0x43,
	0x62, 0x91, 0xda, 0xc1, 0x76, 0xaa, 0xe5, 0x21, 0x00, 0x89, 0x27, 0x46, 0x76, 0x9c, 0x76, 0x25,
	0xd0, 0x72, 0xe1, 0x94, 0x7f, 0xbe, 0x19, 0x65, 0x3e, 0xc5, 0x0e, 0xa4, 0xed, 0x55, 0xbb, 0x68,
	0xb5, 0xb2, 0xea, 0x09, 0x70, 0xa5, 0xb1, 0xcf, 0xc5, 0x35, 0x4c, 0x3f, 0x4a, 0x61, 0x05, 0x6b,
	0xd6, 0x88, 0x9a, 0x64, 0x70, 0xc6, 0xca, 0x52, 0xa3, 0x31, 0x59, 0x94, 0x47, 0xf3, 0x94, 0x0e,
	0xa5, 0xeb, 0xe0, 0x4d, 0x2b, 0x34, 0x9a, 0xec, 0x5e, 0x1e, 0xcd, 0x63, 0x3a, 0x94, 0xc5, 0x23,
	0x78, 0x78, 0xeb, 0x15, 0xef, 0x0e, 0x28, 0xad, 0x29, 0x2e, 0x21, 0x59, 0xf1, 0x55, 0xa3, 0xf8,
	0x17, 0x43, 0x72, 0x98, 0xec, 0x7c, 0xca, 0xa2, 0x7c, 0x34, 0x9f, 0x5e, 0x25, 0x8b, 0xd0, 0xa2,
	0x81, 0x17, 0x5f, 0xe1, 0x6c, 0x83, 0xfa, 0x20, 0x38, 0xba, 0x3d, 0x07, 0xd4, 0x46, 0x28, 0xe9,
	0x0d, 0x62, 0x3a, 0x94, 0x84, 0x40, 0xdc, 0x75, 0xa2, 0xf4, 0xeb, 0x53, 0xea, 0x33, 0x39, 0x87,
	0x51, 0x2b, 0xca, 0x6c, 0xe4, 0x91, 0x8b, 0x6e, 0xca, 0xe2, 0x8d, 0xcd, 0xe2, 0x7e, 0xca, 0x65,
	0xc7, 0x4a, 0x66, 0x59, 0x36, 0xee, 0x99, 0xcb, 0xc5, 0xaf, 0x08, 0x60, 0xdd, 0xd9, 0xff, 0xb5,
	0xf6, 0x19, 0xa4, 0x28, 0xb9, 0xfe, 0xd6, 0x5a, 0x2c, 0xfd, 0xee, 0x84, 0x9e, 0xc0, 0x51, 0x6a,
	0xfc, 0x17, 0xa9, 0x49, 0x1e, 0xcd, 0x67, 0x41, 0xea, 0x7b, 0x04, 0x13, 0x8a, 0x5c, 0xe9, 0xf2,
	0x6e, 0xa1, 0x5a, 0x19, 0x3b, 0x08, 0xb9, 0xec, 0x58, 0xab, 0xb4, 0xf5, 0x46, 0x31, 0xf5, 0x99,
	0x3c, 0x85, 0xb4, 0x61, 0xc6, 0x6e, 0x0d, 0xa2, 0xf4, 0x4a, 0x31, 0x4d, 0x1c, 0xd8, 0x20, 0x4a,
	0x72, 0x01, 0xf7, 0x8f, 0xcd, 0x6d, 0xcd, 0x4c, 0x1d, 0xdc, 0x66, 0xc3, 0xc4, 0x07, 0x66, 0xea,
	0xe2, 0x47, 0x04, 0x93, 0xb7, 0x4a, 0x7e, 0x16, 0xd5, 0x1d, 0x3e, 0xcf, 0x61, 0x66, 0x90, 0x77,
	0x1a, 0xb7, 0xac, 0xdc, 0x0b, 0x19, 0xbc, 0xa6, 0x3d, 0xbb, 0x76, 0xe8, 0xd6, 0x48, 0xa5, 0x55,
	0xd7, 0x86, 0x0f, 0x17, 0x46, 0xde, 0x3b, 0x44, 0x2e, 0x20, 0x31, 0xfd, 0x59, 0x98, 0x2c, 0x0e,
	0xd7, 0x24, 0x1c, 0x0e, 0x3d, 0x76, 0x8a, 0x9f, 0x11, 0xa4, 0xeb, 0xce, 0xfe, 0xd3, 0xe9, 0x31,
	0x8c, 0x4f, 0x32, 0x09, 0xed, 0x0b, 0xf2, 0x12, 0xce, 0x83, 0x86, 0x11, 0x95, 0x64, 0xb6, 0xd3,
	0x18, 0x54, 0x1e, 0xf4, 0x7c, 0x33, 0x60, 0xf2, 0xe2, 0x0f, 0x9d, 0xe9, 0xe2, 0x74, 0x5d, 0x4e,
	0x46, 0xab, 0xcb, 0x4f, 0xaf, 0x2a, 0x61, 0xeb, 0x6e, 0xb7, 0xe0, 0x6a, 0xbf, 0x54, 0x07, 0xd4,
	0x8d, 0x90, 0xf8, 0x7a, 0x2f, 0xa4, 0x90, 0xd5, 0xb2, 0x52, 0xaa, 0x59, 0x1a, 0xcd, 0x97, 0xfe,
	0x6f, 0x33, 0xbb, 0x89, 0x7f, 0xbe, 0xf9, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x09, 0x67, 0x5d, 0x4e,
	0x8e, 0x03, 0x00, 0x00,
}
