// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: protocol.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ObjType int32

const (
	ObjType_BlockHeaders            ObjType = 0
	ObjType_BlockBodies             ObjType = 1
	ObjType_BlockTransactions       ObjType = 2
	ObjType_RoverBestHeights        ObjType = 3
	ObjType_RoverBlockHeaders       ObjType = 4
	ObjType_RoverBlockBodies        ObjType = 5
	ObjType_RoverTransactionHeaders ObjType = 6
	ObjType_RoverMarkedHeaders      ObjType = 7
)

// Enum value maps for ObjType.
var (
	ObjType_name = map[int32]string{
		0: "BlockHeaders",
		1: "BlockBodies",
		2: "BlockTransactions",
		3: "RoverBestHeights",
		4: "RoverBlockHeaders",
		5: "RoverBlockBodies",
		6: "RoverTransactionHeaders",
		7: "RoverMarkedHeaders",
	}
	ObjType_value = map[string]int32{
		"BlockHeaders":            0,
		"BlockBodies":             1,
		"BlockTransactions":       2,
		"RoverBestHeights":        3,
		"RoverBlockHeaders":       4,
		"RoverBlockBodies":        5,
		"RoverTransactionHeaders": 6,
		"RoverMarkedHeaders":      7,
	}
)

func (x ObjType) Enum() *ObjType {
	p := new(ObjType)
	*p = x
	return p
}

func (x ObjType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObjType) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_proto_enumTypes[0].Descriptor()
}

func (ObjType) Type() protoreflect.EnumType {
	return &file_protocol_proto_enumTypes[0]
}

func (x ObjType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ObjType.Descriptor instead.
func (ObjType) EnumDescriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{0}
}

type MsgType int32

const (
	MsgType_GetObjectsRequest MsgType = 0
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0: "GetObjectsRequest",
	}
	MsgType_value = map[string]int32{
		"GetObjectsRequest": 0,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_proto_enumTypes[1].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_protocol_proto_enumTypes[1]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{1}
}

type MessageGetObjectsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type MsgType `protobuf:"varint,1,opt,name=type,proto3,enum=MsgType" json:"type,omitempty"`
	Body ObjType `protobuf:"varint,2,opt,name=body,proto3,enum=ObjType" json:"body,omitempty"`
}

func (x *MessageGetObjectsRequest) Reset() {
	*x = MessageGetObjectsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageGetObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageGetObjectsRequest) ProtoMessage() {}

func (x *MessageGetObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageGetObjectsRequest.ProtoReflect.Descriptor instead.
func (*MessageGetObjectsRequest) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *MessageGetObjectsRequest) GetType() MsgType {
	if x != nil {
		return x.Type
	}
	return MsgType_GetObjectsRequest
}

func (x *MessageGetObjectsRequest) GetBody() ObjType {
	if x != nil {
		return x.Body
	}
	return ObjType_BlockHeaders
}

var File_protocol_proto protoreflect.FileDescriptor

var file_protocol_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x56, 0x0a, 0x18, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x47, 0x65, 0x74, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x08, 0x2e, 0x4d, 0x73, 0x67,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x04, 0x62, 0x6f,
	0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x08, 0x2e, 0x4f, 0x62, 0x6a, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x2a, 0xbb, 0x01, 0x0a, 0x07, 0x4f, 0x62, 0x6a,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x73, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x42,
	0x6f, 0x64, 0x69, 0x65, 0x73, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x10, 0x02, 0x12, 0x14,
	0x0a, 0x10, 0x52, 0x6f, 0x76, 0x65, 0x72, 0x42, 0x65, 0x73, 0x74, 0x48, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x73, 0x10, 0x03, 0x12, 0x15, 0x0a, 0x11, 0x52, 0x6f, 0x76, 0x65, 0x72, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x10, 0x04, 0x12, 0x14, 0x0a, 0x10, 0x52,
	0x6f, 0x76, 0x65, 0x72, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x42, 0x6f, 0x64, 0x69, 0x65, 0x73, 0x10,
	0x05, 0x12, 0x1b, 0x0a, 0x17, 0x52, 0x6f, 0x76, 0x65, 0x72, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x10, 0x06, 0x12, 0x16,
	0x0a, 0x12, 0x52, 0x6f, 0x76, 0x65, 0x72, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x64, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x73, 0x10, 0x07, 0x2a, 0x20, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x15, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x10, 0x00, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x76, 0x65, 0x72, 0x6c, 0x69, 0x6e, 0x65, 0x2d,
	0x6d, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x2f, 0x67, 0x6f, 0x6f, 0x6c, 0x2f, 0x73, 0x72, 0x63, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protocol_proto_rawDescOnce sync.Once
	file_protocol_proto_rawDescData = file_protocol_proto_rawDesc
)

func file_protocol_proto_rawDescGZIP() []byte {
	file_protocol_proto_rawDescOnce.Do(func() {
		file_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(file_protocol_proto_rawDescData)
	})
	return file_protocol_proto_rawDescData
}

var file_protocol_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protocol_proto_goTypes = []interface{}{
	(ObjType)(0),                     // 0: ObjType
	(MsgType)(0),                     // 1: MsgType
	(*MessageGetObjectsRequest)(nil), // 2: MessageGetObjectsRequest
}
var file_protocol_proto_depIdxs = []int32{
	1, // 0: MessageGetObjectsRequest.type:type_name -> MsgType
	0, // 1: MessageGetObjectsRequest.body:type_name -> ObjType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protocol_proto_init() }
func file_protocol_proto_init() {
	if File_protocol_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protocol_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageGetObjectsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocol_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_proto_goTypes,
		DependencyIndexes: file_protocol_proto_depIdxs,
		EnumInfos:         file_protocol_proto_enumTypes,
		MessageInfos:      file_protocol_proto_msgTypes,
	}.Build()
	File_protocol_proto = out.File
	file_protocol_proto_rawDesc = nil
	file_protocol_proto_goTypes = nil
	file_protocol_proto_depIdxs = nil
}
