// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ObjType int32

const (
	ObjType_BlockHeaders            ObjType = 0
	ObjType_BlockBodies             ObjType = 1
	ObjType_BlockTransactions       ObjType = 2
	ObjType_RoverBestHeights        ObjType = 3
	ObjType_RoverBlockHeaders       ObjType = 4
	ObjType_RoverBlockBodies        ObjType = 5
	ObjType_RoverTransactionHeaders ObjType = 6
	ObjType_RoverMarkedHeaders      ObjType = 7
)

var ObjType_name = map[int32]string{
	0: "BlockHeaders",
	1: "BlockBodies",
	2: "BlockTransactions",
	3: "RoverBestHeights",
	4: "RoverBlockHeaders",
	5: "RoverBlockBodies",
	6: "RoverTransactionHeaders",
	7: "RoverMarkedHeaders",
}

var ObjType_value = map[string]int32{
	"BlockHeaders":            0,
	"BlockBodies":             1,
	"BlockTransactions":       2,
	"RoverBestHeights":        3,
	"RoverBlockHeaders":       4,
	"RoverBlockBodies":        5,
	"RoverTransactionHeaders": 6,
	"RoverMarkedHeaders":      7,
}

func (x ObjType) String() string {
	return proto.EnumName(ObjType_name, int32(x))
}

func (ObjType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0}
}

type MsgType int32

const (
	MsgType_GetObjectsRequest MsgType = 0
)

var MsgType_name = map[int32]string{
	0: "GetObjectsRequest",
}

var MsgType_value = map[string]int32{
	"GetObjectsRequest": 0,
}

func (x MsgType) String() string {
	return proto.EnumName(MsgType_name, int32(x))
}

func (MsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{1}
}

type MessageGetObjectsRequest struct {
	Type                 MsgType  `protobuf:"varint,1,opt,name=type,proto3,enum=MsgType" json:"type,omitempty"`
	Body                 ObjType  `protobuf:"varint,2,opt,name=body,proto3,enum=ObjType" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageGetObjectsRequest) Reset()         { *m = MessageGetObjectsRequest{} }
func (m *MessageGetObjectsRequest) String() string { return proto.CompactTextString(m) }
func (*MessageGetObjectsRequest) ProtoMessage()    {}
func (*MessageGetObjectsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0}
}

func (m *MessageGetObjectsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageGetObjectsRequest.Unmarshal(m, b)
}
func (m *MessageGetObjectsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageGetObjectsRequest.Marshal(b, m, deterministic)
}
func (m *MessageGetObjectsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageGetObjectsRequest.Merge(m, src)
}
func (m *MessageGetObjectsRequest) XXX_Size() int {
	return xxx_messageInfo_MessageGetObjectsRequest.Size(m)
}
func (m *MessageGetObjectsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageGetObjectsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageGetObjectsRequest proto.InternalMessageInfo

func (m *MessageGetObjectsRequest) GetType() MsgType {
	if m != nil {
		return m.Type
	}
	return MsgType_GetObjectsRequest
}

func (m *MessageGetObjectsRequest) GetBody() ObjType {
	if m != nil {
		return m.Body
	}
	return ObjType_BlockHeaders
}

func init() {
	proto.RegisterEnum("ObjType", ObjType_name, ObjType_value)
	proto.RegisterEnum("MsgType", MsgType_name, MsgType_value)
	proto.RegisterType((*MessageGetObjectsRequest)(nil), "MessageGetObjectsRequest")
}

func init() { proto.RegisterFile("protocol.proto", fileDescriptor_2bc2336598a3f7e0) }

var fileDescriptor_2bc2336598a3f7e0 = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xdf, 0x4a, 0xc3, 0x30,
	0x14, 0xc6, 0xd7, 0x39, 0x57, 0x89, 0x32, 0x63, 0xf0, 0x4f, 0x41, 0x2f, 0x86, 0x57, 0x52, 0xb4,
	0x05, 0x7d, 0x83, 0xde, 0xb8, 0x9b, 0x32, 0x28, 0xc3, 0x0b, 0xef, 0xda, 0xf4, 0x90, 0x65, 0xeb,
	0x7a, 0x6a, 0x4e, 0x26, 0xf4, 0xd9, 0x7c, 0x39, 0x69, 0xd6, 0x61, 0xc1, 0xab, 0x84, 0xdf, 0x77,
	0xf2, 0x0b, 0xe7, 0x63, 0xb3, 0xc6, 0xa0, 0x45, 0x89, 0x55, 0xe4, 0x2e, 0x8f, 0x1f, 0x2c, 0x48,
	0x81, 0x28, 0x57, 0xf0, 0x0e, 0x76, 0x59, 0x6c, 0x40, 0x5a, 0xca, 0xe0, 0x6b, 0x0f, 0x64, 0xc5,
	0x03, 0x9b, 0xd8, 0xb6, 0x81, 0xc0, 0x9b, 0x7b, 0x4f, 0xb3, 0xd7, 0xb3, 0x28, 0x25, 0xb5, 0x6a,
	0x1b, 0xc8, 0x1c, 0xed, 0xd2, 0x02, 0xcb, 0x36, 0x18, 0xf7, 0xe9, 0xb2, 0xd8, 0x1c, 0xd2, 0x8e,
	0x86, 0x3f, 0x1e, 0xf3, 0x7b, 0x22, 0x38, 0xbb, 0x48, 0x2a, 0x94, 0xdb, 0x05, 0xe4, 0x25, 0x18,
	0xe2, 0x23, 0x71, 0xc9, 0xce, 0x1d, 0x49, 0xb0, 0xd4, 0x40, 0xdc, 0x13, 0x37, 0xec, 0xca, 0x81,
	0x95, 0xc9, 0x6b, 0xca, 0xa5, 0xd5, 0x58, 0x13, 0x1f, 0x8b, 0x6b, 0xc6, 0x33, 0xfc, 0x06, 0x93,
	0x00, 0xd9, 0x05, 0x68, 0xb5, 0xb6, 0xc4, 0x4f, 0xba, 0xe1, 0x03, 0x1d, 0x4a, 0x27, 0x7f, 0xc3,
	0x03, 0xf3, 0xa9, 0xb8, 0x67, 0x77, 0x8e, 0x0e, 0xcc, 0xc7, 0x27, 0x53, 0x71, 0xcb, 0x84, 0x0b,
	0xd3, 0xdc, 0x6c, 0xa1, 0x3c, 0x72, 0x3f, 0x9c, 0x33, 0xbf, 0x5f, 0xb6, 0xfb, 0xec, 0x5f, 0x33,
	0x7c, 0x94, 0x3c, 0x7f, 0x86, 0x4a, 0xdb, 0xf5, 0xbe, 0x88, 0x24, 0xee, 0xe2, 0xce, 0x51, 0xe9,
	0x1a, 0x5e, 0x76, 0xba, 0xd6, 0xb5, 0x8a, 0x15, 0x62, 0x15, 0x93, 0x91, 0xb1, 0x2b, 0x99, 0x8a,
	0xa9, 0x3b, 0xdf, 0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x8b, 0xae, 0x97, 0x7e, 0x01, 0x00,
	0x00,
}
