// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rover.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RoverMessageType int32

const (
	RoverMessageType_FetchBlock        RoverMessageType = 0
	RoverMessageType_RequestResync     RoverMessageType = 1
	RoverMessageType_rover_block_range RoverMessageType = 2
)

var RoverMessageType_name = map[int32]string{
	0: "FetchBlock",
	1: "RequestResync",
	2: "rover_block_range",
}

var RoverMessageType_value = map[string]int32{
	"FetchBlock":        0,
	"RequestResync":     1,
	"rover_block_range": 2,
}

func (x RoverMessageType) String() string {
	return proto.EnumName(RoverMessageType_name, int32(x))
}

func (RoverMessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a2b4b2643fc791e2, []int{0}
}

type RoverIdent struct {
	RoverName            string   `protobuf:"bytes,1,opt,name=rover_name,json=roverName,proto3" json:"rover_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoverIdent) Reset()         { *m = RoverIdent{} }
func (m *RoverIdent) String() string { return proto.CompactTextString(m) }
func (*RoverIdent) ProtoMessage()    {}
func (*RoverIdent) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2b4b2643fc791e2, []int{0}
}

func (m *RoverIdent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoverIdent.Unmarshal(m, b)
}
func (m *RoverIdent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoverIdent.Marshal(b, m, deterministic)
}
func (m *RoverIdent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoverIdent.Merge(m, src)
}
func (m *RoverIdent) XXX_Size() int {
	return xxx_messageInfo_RoverIdent.Size(m)
}
func (m *RoverIdent) XXX_DiscardUnknown() {
	xxx_messageInfo_RoverIdent.DiscardUnknown(m)
}

var xxx_messageInfo_RoverIdent proto.InternalMessageInfo

func (m *RoverIdent) GetRoverName() string {
	if m != nil {
		return m.RoverName
	}
	return ""
}

type RoverSyncStatus struct {
	RoverName            string   `protobuf:"bytes,1,opt,name=rover_name,json=roverName,proto3" json:"rover_name,omitempty"`
	Status               bool     `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoverSyncStatus) Reset()         { *m = RoverSyncStatus{} }
func (m *RoverSyncStatus) String() string { return proto.CompactTextString(m) }
func (*RoverSyncStatus) ProtoMessage()    {}
func (*RoverSyncStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2b4b2643fc791e2, []int{1}
}

func (m *RoverSyncStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoverSyncStatus.Unmarshal(m, b)
}
func (m *RoverSyncStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoverSyncStatus.Marshal(b, m, deterministic)
}
func (m *RoverSyncStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoverSyncStatus.Merge(m, src)
}
func (m *RoverSyncStatus) XXX_Size() int {
	return xxx_messageInfo_RoverSyncStatus.Size(m)
}
func (m *RoverSyncStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_RoverSyncStatus.DiscardUnknown(m)
}

var xxx_messageInfo_RoverSyncStatus proto.InternalMessageInfo

func (m *RoverSyncStatus) GetRoverName() string {
	if m != nil {
		return m.RoverName
	}
	return ""
}

func (m *RoverSyncStatus) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type RoverMessage struct {
	Type RoverMessageType `protobuf:"varint,1,opt,name=type,proto3,enum=RoverMessageType" json:"type,omitempty"`
	// Types that are valid to be assigned to Payload:
	//	*RoverMessage_Resync_
	//	*RoverMessage_FetchBlock_
	//	*RoverMessage_RoverBlockRange_
	Payload              isRoverMessage_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *RoverMessage) Reset()         { *m = RoverMessage{} }
func (m *RoverMessage) String() string { return proto.CompactTextString(m) }
func (*RoverMessage) ProtoMessage()    {}
func (*RoverMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2b4b2643fc791e2, []int{2}
}

func (m *RoverMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoverMessage.Unmarshal(m, b)
}
func (m *RoverMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoverMessage.Marshal(b, m, deterministic)
}
func (m *RoverMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoverMessage.Merge(m, src)
}
func (m *RoverMessage) XXX_Size() int {
	return xxx_messageInfo_RoverMessage.Size(m)
}
func (m *RoverMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RoverMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RoverMessage proto.InternalMessageInfo

func (m *RoverMessage) GetType() RoverMessageType {
	if m != nil {
		return m.Type
	}
	return RoverMessageType_FetchBlock
}

type isRoverMessage_Payload interface {
	isRoverMessage_Payload()
}

type RoverMessage_Resync_ struct {
	Resync *RoverMessage_Resync `protobuf:"bytes,2,opt,name=resync,proto3,oneof"`
}

type RoverMessage_FetchBlock_ struct {
	FetchBlock *RoverMessage_FetchBlock `protobuf:"bytes,3,opt,name=fetch_block,json=fetchBlock,proto3,oneof"`
}

type RoverMessage_RoverBlockRange_ struct {
	RoverBlockRange *RoverMessage_RoverBlockRange `protobuf:"bytes,4,opt,name=rover_block_range,json=roverBlockRange,proto3,oneof"`
}

func (*RoverMessage_Resync_) isRoverMessage_Payload() {}

func (*RoverMessage_FetchBlock_) isRoverMessage_Payload() {}

func (*RoverMessage_RoverBlockRange_) isRoverMessage_Payload() {}

func (m *RoverMessage) GetPayload() isRoverMessage_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *RoverMessage) GetResync() *RoverMessage_Resync {
	if x, ok := m.GetPayload().(*RoverMessage_Resync_); ok {
		return x.Resync
	}
	return nil
}

func (m *RoverMessage) GetFetchBlock() *RoverMessage_FetchBlock {
	if x, ok := m.GetPayload().(*RoverMessage_FetchBlock_); ok {
		return x.FetchBlock
	}
	return nil
}

func (m *RoverMessage) GetRoverBlockRange() *RoverMessage_RoverBlockRange {
	if x, ok := m.GetPayload().(*RoverMessage_RoverBlockRange_); ok {
		return x.RoverBlockRange
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RoverMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RoverMessage_Resync_)(nil),
		(*RoverMessage_FetchBlock_)(nil),
		(*RoverMessage_RoverBlockRange_)(nil),
	}
}

type RoverMessage_FetchBlock struct {
	FromBlock            *Block   `protobuf:"bytes,1,opt,name=from_block,json=fromBlock,proto3" json:"from_block,omitempty"`
	ToBlock              *Block   `protobuf:"bytes,2,opt,name=to_block,json=toBlock,proto3" json:"to_block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoverMessage_FetchBlock) Reset()         { *m = RoverMessage_FetchBlock{} }
func (m *RoverMessage_FetchBlock) String() string { return proto.CompactTextString(m) }
func (*RoverMessage_FetchBlock) ProtoMessage()    {}
func (*RoverMessage_FetchBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2b4b2643fc791e2, []int{2, 0}
}

func (m *RoverMessage_FetchBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoverMessage_FetchBlock.Unmarshal(m, b)
}
func (m *RoverMessage_FetchBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoverMessage_FetchBlock.Marshal(b, m, deterministic)
}
func (m *RoverMessage_FetchBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoverMessage_FetchBlock.Merge(m, src)
}
func (m *RoverMessage_FetchBlock) XXX_Size() int {
	return xxx_messageInfo_RoverMessage_FetchBlock.Size(m)
}
func (m *RoverMessage_FetchBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_RoverMessage_FetchBlock.DiscardUnknown(m)
}

var xxx_messageInfo_RoverMessage_FetchBlock proto.InternalMessageInfo

func (m *RoverMessage_FetchBlock) GetFromBlock() *Block {
	if m != nil {
		return m.FromBlock
	}
	return nil
}

func (m *RoverMessage_FetchBlock) GetToBlock() *Block {
	if m != nil {
		return m.ToBlock
	}
	return nil
}

type RoverMessage_RoverBlockRange struct {
	RoverName            string   `protobuf:"bytes,1,opt,name=rover_name,json=roverName,proto3" json:"rover_name,omitempty"`
	HighestHeight        uint64   `protobuf:"varint,2,opt,name=highest_height,json=highestHeight,proto3" json:"highest_height,omitempty"`
	LowestHeight         uint64   `protobuf:"varint,3,opt,name=lowest_height,json=lowestHeight,proto3" json:"lowest_height,omitempty"`
	HighestHash          string   `protobuf:"bytes,4,opt,name=highest_hash,json=highestHash,proto3" json:"highest_hash,omitempty"`
	LowestHash           string   `protobuf:"bytes,5,opt,name=lowest_hash,json=lowestHash,proto3" json:"lowest_hash,omitempty"`
	Synced               string   `protobuf:"bytes,6,opt,name=synced,proto3" json:"synced,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoverMessage_RoverBlockRange) Reset()         { *m = RoverMessage_RoverBlockRange{} }
func (m *RoverMessage_RoverBlockRange) String() string { return proto.CompactTextString(m) }
func (*RoverMessage_RoverBlockRange) ProtoMessage()    {}
func (*RoverMessage_RoverBlockRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2b4b2643fc791e2, []int{2, 1}
}

func (m *RoverMessage_RoverBlockRange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoverMessage_RoverBlockRange.Unmarshal(m, b)
}
func (m *RoverMessage_RoverBlockRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoverMessage_RoverBlockRange.Marshal(b, m, deterministic)
}
func (m *RoverMessage_RoverBlockRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoverMessage_RoverBlockRange.Merge(m, src)
}
func (m *RoverMessage_RoverBlockRange) XXX_Size() int {
	return xxx_messageInfo_RoverMessage_RoverBlockRange.Size(m)
}
func (m *RoverMessage_RoverBlockRange) XXX_DiscardUnknown() {
	xxx_messageInfo_RoverMessage_RoverBlockRange.DiscardUnknown(m)
}

var xxx_messageInfo_RoverMessage_RoverBlockRange proto.InternalMessageInfo

func (m *RoverMessage_RoverBlockRange) GetRoverName() string {
	if m != nil {
		return m.RoverName
	}
	return ""
}

func (m *RoverMessage_RoverBlockRange) GetHighestHeight() uint64 {
	if m != nil {
		return m.HighestHeight
	}
	return 0
}

func (m *RoverMessage_RoverBlockRange) GetLowestHeight() uint64 {
	if m != nil {
		return m.LowestHeight
	}
	return 0
}

func (m *RoverMessage_RoverBlockRange) GetHighestHash() string {
	if m != nil {
		return m.HighestHash
	}
	return ""
}

func (m *RoverMessage_RoverBlockRange) GetLowestHash() string {
	if m != nil {
		return m.LowestHash
	}
	return ""
}

func (m *RoverMessage_RoverBlockRange) GetSynced() string {
	if m != nil {
		return m.Synced
	}
	return ""
}

type RoverMessage_Resync struct {
	// latest know block we have in storage, can be empty
	LatestBlock          *Block                          `protobuf:"bytes,1,opt,name=latest_block,json=latestBlock,proto3" json:"latest_block,omitempty"`
	Intervals            []*RoverMessage_Resync_Interval `protobuf:"bytes,2,rep,name=intervals,proto3" json:"intervals,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *RoverMessage_Resync) Reset()         { *m = RoverMessage_Resync{} }
func (m *RoverMessage_Resync) String() string { return proto.CompactTextString(m) }
func (*RoverMessage_Resync) ProtoMessage()    {}
func (*RoverMessage_Resync) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2b4b2643fc791e2, []int{2, 2}
}

func (m *RoverMessage_Resync) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoverMessage_Resync.Unmarshal(m, b)
}
func (m *RoverMessage_Resync) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoverMessage_Resync.Marshal(b, m, deterministic)
}
func (m *RoverMessage_Resync) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoverMessage_Resync.Merge(m, src)
}
func (m *RoverMessage_Resync) XXX_Size() int {
	return xxx_messageInfo_RoverMessage_Resync.Size(m)
}
func (m *RoverMessage_Resync) XXX_DiscardUnknown() {
	xxx_messageInfo_RoverMessage_Resync.DiscardUnknown(m)
}

var xxx_messageInfo_RoverMessage_Resync proto.InternalMessageInfo

func (m *RoverMessage_Resync) GetLatestBlock() *Block {
	if m != nil {
		return m.LatestBlock
	}
	return nil
}

func (m *RoverMessage_Resync) GetIntervals() []*RoverMessage_Resync_Interval {
	if m != nil {
		return m.Intervals
	}
	return nil
}

type RoverMessage_Resync_Interval struct {
	FromBlock            *Block   `protobuf:"bytes,1,opt,name=from_block,json=fromBlock,proto3" json:"from_block,omitempty"`
	ToBlock              *Block   `protobuf:"bytes,2,opt,name=to_block,json=toBlock,proto3" json:"to_block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoverMessage_Resync_Interval) Reset()         { *m = RoverMessage_Resync_Interval{} }
func (m *RoverMessage_Resync_Interval) String() string { return proto.CompactTextString(m) }
func (*RoverMessage_Resync_Interval) ProtoMessage()    {}
func (*RoverMessage_Resync_Interval) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2b4b2643fc791e2, []int{2, 2, 0}
}

func (m *RoverMessage_Resync_Interval) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoverMessage_Resync_Interval.Unmarshal(m, b)
}
func (m *RoverMessage_Resync_Interval) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoverMessage_Resync_Interval.Marshal(b, m, deterministic)
}
func (m *RoverMessage_Resync_Interval) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoverMessage_Resync_Interval.Merge(m, src)
}
func (m *RoverMessage_Resync_Interval) XXX_Size() int {
	return xxx_messageInfo_RoverMessage_Resync_Interval.Size(m)
}
func (m *RoverMessage_Resync_Interval) XXX_DiscardUnknown() {
	xxx_messageInfo_RoverMessage_Resync_Interval.DiscardUnknown(m)
}

var xxx_messageInfo_RoverMessage_Resync_Interval proto.InternalMessageInfo

func (m *RoverMessage_Resync_Interval) GetFromBlock() *Block {
	if m != nil {
		return m.FromBlock
	}
	return nil
}

func (m *RoverMessage_Resync_Interval) GetToBlock() *Block {
	if m != nil {
		return m.ToBlock
	}
	return nil
}

type SettleTxCheckReq struct {
	PossibleTransactions []*SettleTxCheckReq_PossibleTransaction `protobuf:"bytes,1,rep,name=possible_transactions,json=possibleTransactions,proto3" json:"possible_transactions,omitempty"`
	BlockHash            string                                  `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *SettleTxCheckReq) Reset()         { *m = SettleTxCheckReq{} }
func (m *SettleTxCheckReq) String() string { return proto.CompactTextString(m) }
func (*SettleTxCheckReq) ProtoMessage()    {}
func (*SettleTxCheckReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2b4b2643fc791e2, []int{3}
}

func (m *SettleTxCheckReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SettleTxCheckReq.Unmarshal(m, b)
}
func (m *SettleTxCheckReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SettleTxCheckReq.Marshal(b, m, deterministic)
}
func (m *SettleTxCheckReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettleTxCheckReq.Merge(m, src)
}
func (m *SettleTxCheckReq) XXX_Size() int {
	return xxx_messageInfo_SettleTxCheckReq.Size(m)
}
func (m *SettleTxCheckReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SettleTxCheckReq.DiscardUnknown(m)
}

var xxx_messageInfo_SettleTxCheckReq proto.InternalMessageInfo

func (m *SettleTxCheckReq) GetPossibleTransactions() []*SettleTxCheckReq_PossibleTransaction {
	if m != nil {
		return m.PossibleTransactions
	}
	return nil
}

func (m *SettleTxCheckReq) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

type SettleTxCheckReq_PossibleTransaction struct {
	AddrTo               string   `protobuf:"bytes,1,opt,name=addr_to,json=addrTo,proto3" json:"addr_to,omitempty"`
	AddrFrom             string   `protobuf:"bytes,2,opt,name=addr_from,json=addrFrom,proto3" json:"addr_from,omitempty"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	BridgedChain         string   `protobuf:"bytes,4,opt,name=bridged_chain,json=bridgedChain,proto3" json:"bridged_chain,omitempty"`
	TxId                 string   `protobuf:"bytes,5,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	BlockHeight          uint64   `protobuf:"varint,6,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	TokenType            string   `protobuf:"bytes,7,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SettleTxCheckReq_PossibleTransaction) Reset()         { *m = SettleTxCheckReq_PossibleTransaction{} }
func (m *SettleTxCheckReq_PossibleTransaction) String() string { return proto.CompactTextString(m) }
func (*SettleTxCheckReq_PossibleTransaction) ProtoMessage()    {}
func (*SettleTxCheckReq_PossibleTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2b4b2643fc791e2, []int{3, 0}
}

func (m *SettleTxCheckReq_PossibleTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SettleTxCheckReq_PossibleTransaction.Unmarshal(m, b)
}
func (m *SettleTxCheckReq_PossibleTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SettleTxCheckReq_PossibleTransaction.Marshal(b, m, deterministic)
}
func (m *SettleTxCheckReq_PossibleTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettleTxCheckReq_PossibleTransaction.Merge(m, src)
}
func (m *SettleTxCheckReq_PossibleTransaction) XXX_Size() int {
	return xxx_messageInfo_SettleTxCheckReq_PossibleTransaction.Size(m)
}
func (m *SettleTxCheckReq_PossibleTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_SettleTxCheckReq_PossibleTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_SettleTxCheckReq_PossibleTransaction proto.InternalMessageInfo

func (m *SettleTxCheckReq_PossibleTransaction) GetAddrTo() string {
	if m != nil {
		return m.AddrTo
	}
	return ""
}

func (m *SettleTxCheckReq_PossibleTransaction) GetAddrFrom() string {
	if m != nil {
		return m.AddrFrom
	}
	return ""
}

func (m *SettleTxCheckReq_PossibleTransaction) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *SettleTxCheckReq_PossibleTransaction) GetBridgedChain() string {
	if m != nil {
		return m.BridgedChain
	}
	return ""
}

func (m *SettleTxCheckReq_PossibleTransaction) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func (m *SettleTxCheckReq_PossibleTransaction) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *SettleTxCheckReq_PossibleTransaction) GetTokenType() string {
	if m != nil {
		return m.TokenType
	}
	return ""
}

type SettleTxCheckResponse struct {
	MarkedTransactions   []*MarkedTransaction `protobuf:"bytes,1,rep,name=marked_transactions,json=markedTransactions,proto3" json:"marked_transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SettleTxCheckResponse) Reset()         { *m = SettleTxCheckResponse{} }
func (m *SettleTxCheckResponse) String() string { return proto.CompactTextString(m) }
func (*SettleTxCheckResponse) ProtoMessage()    {}
func (*SettleTxCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2b4b2643fc791e2, []int{4}
}

func (m *SettleTxCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SettleTxCheckResponse.Unmarshal(m, b)
}
func (m *SettleTxCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SettleTxCheckResponse.Marshal(b, m, deterministic)
}
func (m *SettleTxCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettleTxCheckResponse.Merge(m, src)
}
func (m *SettleTxCheckResponse) XXX_Size() int {
	return xxx_messageInfo_SettleTxCheckResponse.Size(m)
}
func (m *SettleTxCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SettleTxCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SettleTxCheckResponse proto.InternalMessageInfo

func (m *SettleTxCheckResponse) GetMarkedTransactions() []*MarkedTransaction {
	if m != nil {
		return m.MarkedTransactions
	}
	return nil
}

func init() {
	proto.RegisterEnum("RoverMessageType", RoverMessageType_name, RoverMessageType_value)
	proto.RegisterType((*RoverIdent)(nil), "RoverIdent")
	proto.RegisterType((*RoverSyncStatus)(nil), "RoverSyncStatus")
	proto.RegisterType((*RoverMessage)(nil), "RoverMessage")
	proto.RegisterType((*RoverMessage_FetchBlock)(nil), "RoverMessage.FetchBlock")
	proto.RegisterType((*RoverMessage_RoverBlockRange)(nil), "RoverMessage.RoverBlockRange")
	proto.RegisterType((*RoverMessage_Resync)(nil), "RoverMessage.Resync")
	proto.RegisterType((*RoverMessage_Resync_Interval)(nil), "RoverMessage.Resync.Interval")
	proto.RegisterType((*SettleTxCheckReq)(nil), "SettleTxCheckReq")
	proto.RegisterType((*SettleTxCheckReq_PossibleTransaction)(nil), "SettleTxCheckReq.PossibleTransaction")
	proto.RegisterType((*SettleTxCheckResponse)(nil), "SettleTxCheckResponse")
}

func init() { proto.RegisterFile("rover.proto", fileDescriptor_a2b4b2643fc791e2) }

var fileDescriptor_a2b4b2643fc791e2 = []byte{
	// 813 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x4d, 0x6f, 0xdb, 0x46,
	0x10, 0x15, 0x65, 0x49, 0xb6, 0x46, 0xb2, 0x23, 0xaf, 0xed, 0x54, 0x60, 0x61, 0x34, 0x51, 0xe1,
	0xc2, 0x4d, 0x1b, 0xba, 0x70, 0x6f, 0xcd, 0xcd, 0x02, 0x02, 0xb9, 0x6d, 0x82, 0x62, 0x2d, 0xf4,
	0x10, 0x14, 0x20, 0x56, 0xe4, 0x58, 0x24, 0x4c, 0x71, 0x95, 0xdd, 0x95, 0x6b, 0x5d, 0xfb, 0xe3,
	0xfa, 0x1b, 0x7a, 0xe9, 0x4f, 0xe8, 0xb5, 0xe7, 0x62, 0x67, 0x57, 0xd6, 0x47, 0x84, 0xe6, 0x92,
	0x93, 0x38, 0x6f, 0xde, 0xbc, 0x5d, 0xce, 0x3c, 0x8e, 0xa0, 0xa5, 0xe4, 0x3d, 0xaa, 0x68, 0xaa,
	0xa4, 0x91, 0x21, 0x24, 0x52, 0xa1, 0x7b, 0xee, 0x7d, 0x03, 0xc0, 0x6d, 0xea, 0x3a, 0xc5, 0xd2,
	0xb0, 0x53, 0x00, 0x22, 0xc6, 0xa5, 0x98, 0x60, 0x37, 0x78, 0x16, 0x9c, 0x37, 0x79, 0x93, 0x90,
	0xb7, 0x62, 0x82, 0xbd, 0x01, 0x3c, 0x21, 0xf2, 0xcd, 0xbc, 0x4c, 0x6e, 0x8c, 0x30, 0x33, 0xfd,
	0x91, 0x0a, 0xf6, 0x14, 0x1a, 0x9a, 0x88, 0xdd, 0xea, 0xb3, 0xe0, 0x7c, 0x8f, 0xfb, 0xa8, 0xf7,
	0x6f, 0x1d, 0xda, 0x24, 0xf5, 0x06, 0xb5, 0x16, 0x63, 0x64, 0x67, 0x50, 0x33, 0xf3, 0xa9, 0x53,
	0x38, 0xb8, 0x3c, 0x8c, 0x56, 0x93, 0xc3, 0xf9, 0x14, 0x39, 0xa5, 0x59, 0x04, 0x0d, 0x85, 0x7a,
	0x5e, 0x26, 0xa4, 0xd7, 0xba, 0x3c, 0x5e, 0x23, 0x46, 0x9c, 0x72, 0x83, 0x0a, 0xf7, 0x2c, 0xf6,
	0x0a, 0x5a, 0xb7, 0x68, 0x92, 0x2c, 0x1e, 0x15, 0x32, 0xb9, 0xeb, 0xee, 0x50, 0x51, 0x77, 0xbd,
	0xe8, 0xb5, 0x25, 0x5c, 0xd9, 0xfc, 0xa0, 0xc2, 0xe1, 0xf6, 0x31, 0x62, 0x3f, 0xc1, 0xa1, 0x7b,
	0x37, 0x2a, 0x8e, 0x95, 0x28, 0xc7, 0xd8, 0xad, 0x91, 0xc4, 0xe9, 0xc6, 0xb9, 0x36, 0xa0, 0x22,
	0x6e, 0x49, 0x83, 0x0a, 0x7f, 0xa2, 0xd6, 0xa1, 0xf0, 0x57, 0x80, 0xe5, 0x41, 0xec, 0x0c, 0xe0,
	0x56, 0xc9, 0x89, 0xbf, 0x56, 0x40, 0x9a, 0x8d, 0xc8, 0xd1, 0x9b, 0x36, 0xe3, 0x68, 0xcf, 0x61,
	0xcf, 0x48, 0x4f, 0xaa, 0xae, 0x91, 0x76, 0x8d, 0xa4, 0x87, 0xf0, 0xaf, 0xc0, 0x0f, 0x65, 0x79,
	0xd6, 0xc7, 0x86, 0x72, 0x06, 0x07, 0x59, 0x3e, 0xce, 0x50, 0x9b, 0x38, 0xc3, 0x7c, 0x9c, 0x19,
	0xd2, 0xae, 0xf1, 0x7d, 0x8f, 0x0e, 0x08, 0x64, 0x5f, 0xc2, 0x7e, 0x21, 0x7f, 0x5f, 0x61, 0xed,
	0x10, 0xab, 0xed, 0x40, 0x4f, 0x7a, 0x0e, 0xed, 0x47, 0x2d, 0xa1, 0x33, 0x6a, 0x4f, 0x93, 0xb7,
	0x16, 0x4a, 0x42, 0x67, 0xec, 0x0b, 0x68, 0x2d, 0x74, 0x2c, 0xa3, 0x4e, 0x0c, 0xf0, 0x2a, 0x96,
	0x60, 0x4d, 0x32, 0x2f, 0x13, 0x4c, 0xbb, 0x0d, 0xca, 0xf9, 0x28, 0xfc, 0x33, 0x80, 0x86, 0x9b,
	0x28, 0xfb, 0x1a, 0xda, 0x85, 0x30, 0x56, 0x63, 0x5b, 0xc7, 0x5a, 0x2e, 0xe7, 0x7a, 0xf6, 0x0a,
	0x9a, 0x79, 0x69, 0x50, 0xdd, 0x8b, 0xc2, 0xba, 0x6e, 0x67, 0xcb, 0xb4, 0x48, 0x33, 0xba, 0xf6,
	0x2c, 0xbe, 0xe4, 0x87, 0x43, 0xd8, 0x5b, 0xc0, 0x9f, 0x6e, 0x46, 0x57, 0x4d, 0xd8, 0x9d, 0x8a,
	0x79, 0x21, 0x45, 0xda, 0xfb, 0xa7, 0x0a, 0x9d, 0x1b, 0x34, 0xa6, 0xc0, 0xe1, 0x43, 0x3f, 0xc3,
	0xe4, 0x8e, 0xe3, 0x7b, 0xf6, 0x0e, 0x4e, 0xa6, 0x52, 0xeb, 0x7c, 0x54, 0x60, 0x6c, 0x94, 0x28,
	0xb5, 0x48, 0x4c, 0x2e, 0x4b, 0xdd, 0x0d, 0xe8, 0xfa, 0x67, 0xd1, 0x66, 0x45, 0xf4, 0x8b, 0xa7,
	0x0f, 0x97, 0x6c, 0x7e, 0x3c, 0xfd, 0x10, 0xa4, 0x0f, 0xd4, 0xd9, 0x97, 0x9a, 0x5f, 0x75, 0x5e,
	0x20, 0xc4, 0xf6, 0x3e, 0xfc, 0x3b, 0x80, 0xa3, 0x2d, 0x62, 0xec, 0x33, 0xd8, 0x15, 0x69, 0xaa,
	0x62, 0x23, 0xbd, 0x7f, 0x1a, 0x36, 0x1c, 0x4a, 0xf6, 0x39, 0x34, 0x29, 0x61, 0x1b, 0xe0, 0xe5,
	0xf6, 0x2c, 0xf0, 0x5a, 0xc9, 0x09, 0x3b, 0x86, 0xfa, 0xbd, 0x28, 0x66, 0x48, 0x56, 0x69, 0x73,
	0x17, 0x58, 0x23, 0x8d, 0x54, 0x9e, 0x8e, 0x31, 0x8d, 0x93, 0x4c, 0xe4, 0xa5, 0x37, 0x49, 0xdb,
	0x83, 0x7d, 0x8b, 0xb1, 0x23, 0xa8, 0x9b, 0x87, 0x38, 0x4f, 0xbd, 0x3f, 0x6a, 0xe6, 0xe1, 0x3a,
	0xb5, 0xee, 0xf2, 0x97, 0x77, 0x0e, 0x6c, 0x90, 0x03, 0x5b, 0xee, 0xfa, 0xce, 0x80, 0xa7, 0x00,
	0x46, 0xde, 0x61, 0x19, 0xd3, 0xfa, 0xd8, 0x75, 0xef, 0x47, 0x88, 0x5d, 0x1b, 0xbd, 0xdf, 0xe0,
	0x64, 0xa3, 0x79, 0x7a, 0x2a, 0x4b, 0x8d, 0xac, 0x0f, 0x47, 0x13, 0xa1, 0xee, 0x30, 0xdd, 0xd6,
	0x71, 0x16, 0xbd, 0xa1, 0xdc, 0x6a, 0x7b, 0xd9, 0x64, 0x13, 0xd2, 0x2f, 0x7e, 0x86, 0xce, 0xe6,
	0xa2, 0x62, 0x07, 0xab, 0x1f, 0x7a, 0xa7, 0xc2, 0x0e, 0x61, 0x9f, 0xe3, 0xfb, 0x19, 0x6a, 0xe3,
	0x7c, 0xd7, 0x09, 0xd8, 0xc9, 0x96, 0xc5, 0xd2, 0xa9, 0x5e, 0xfe, 0x51, 0x85, 0x3a, 0xc9, 0xb1,
	0xaf, 0xa0, 0xf6, 0xa3, 0xcc, 0x4b, 0xd6, 0x8a, 0x96, 0xcb, 0x39, 0xdc, 0x5f, 0x73, 0x71, 0xaf,
	0xf2, 0x5d, 0x60, 0xfb, 0xd3, 0x97, 0x45, 0x81, 0x89, 0xf7, 0xbe, 0x77, 0x5e, 0x58, 0x8f, 0xde,
	0xce, 0x8a, 0xa2, 0x57, 0x39, 0x0f, 0xd8, 0x4b, 0xe8, 0x70, 0x9c, 0x4a, 0x65, 0x56, 0x96, 0x76,
	0x27, 0xda, 0x58, 0xe3, 0x8f, 0x05, 0xec, 0x87, 0x05, 0x7d, 0x75, 0x9d, 0xfc, 0xef, 0xb2, 0x5b,
	0xd6, 0xf6, 0xe1, 0xf8, 0x5a, 0x5f, 0xe1, 0xad, 0x54, 0xe8, 0x7a, 0xee, 0x47, 0x74, 0xf8, 0x81,
	0x7f, 0xc3, 0xa7, 0xd1, 0xd6, 0xa9, 0xf4, 0x2a, 0x57, 0xdf, 0xbe, 0x7b, 0x31, 0xce, 0x4d, 0x36,
	0x1b, 0x45, 0x89, 0x9c, 0x5c, 0xd8, 0xa3, 0x8a, 0xbc, 0xc4, 0x97, 0x93, 0xbc, 0xcc, 0xcb, 0xf1,
	0xc5, 0x58, 0xca, 0xe2, 0x42, 0xab, 0xe4, 0x82, 0xfe, 0xbd, 0xf4, 0xa8, 0x41, 0xbf, 0xdf, 0xff,
	0x17, 0x00, 0x00, 0xff, 0xff, 0x41, 0x78, 0xa5, 0xfb, 0xe0, 0x06, 0x00, 0x00,
}
