name: deploy gool docker images

on:
  push:
    tags:
    - v*.*.*

jobs:
  gool:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_ACCOUNT }} --password-stdin
      -
        name: Build and push all targets
        run: |
          TAG=$(git describe --tags --abbrev=0)
          BUILD=$(git rev-parse --short HEAD)
          VERSION=${TAG}-g${BUILD}

          PLATFORMS=linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v5,linux/mips64le

          docker buildx build --progress plain --platform ${PLATFORMS} --tag ${{ secrets.DOCKERHUB_ACCOUNT }}/gool:${VERSION} -f docker/Dockerfile.gool . --push
          docker buildx build --progress plain --platform ${PLATFORMS} --tag ${{ secrets.DOCKERHUB_ACCOUNT }}/gool:latest -f docker/Dockerfile.gool . --push
